local/local/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve

app_name = 'serv'

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('serv.urls', namespace='')),
]


if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local/serv/urls.py
from django.urls import path
from .views import (index, profile, ServLogoutView, register, LoginUser, request_add, design_request_list,
                    request_detail, category_list, add_category, DeleteCategoryView, all_requests,
                    ChangeStatusToDoneView, ChangeStatusToCompletedView)
from .views import DeleteRequestView

app_name = 'serv'


urlpatterns = [
   path('', index, name='index'),
   path('login/', LoginUser.as_view(), name='login'),
   path('logout/', ServLogoutView.as_view(), name='logout'),
   path('accounts/profile/', profile, name='profile'),
   path('register/', register, name='register'),
   path('request/add/', request_add, name='request_add'),
   path('request/delete/<int:id>/', DeleteRequestView.as_view(), name='profile_request_delete'),
   path('request/list/', design_request_list, name='design_request_list'),
   path('request/detail/', request_detail, name='request_detail'),
   path('requests/all/', all_requests, name='all_requests'),
   path('status/to_done/<int:id>/', ChangeStatusToDoneView.as_view(), name='change_status_to_done'),
   path('status/to_completed/<int:id>/', ChangeStatusToCompletedView.as_view(), name='change_status_to_completed'),
   path('category/list/', category_list, name='category_list'),
   path('category/add/', add_category, name='add_category'),
   path('category/delete/<int:id>/', DeleteCategoryView.as_view(), name='delete_category'),
]

local/serv/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image

class ServUser(AbstractUser):
    surname = models.CharField(max_length=255, verbose_name='Фамилия')
    name = models.CharField(max_length=255, verbose_name='Имя')
    patronymic = models.CharField(max_length=255, verbose_name='Отчество')
    username = models.CharField(max_length=255, unique=True, verbose_name='Логин', db_column='username')
    email = models.EmailField(unique=True, verbose_name='Email')
    consent = models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')

    def clean(self):
        if not self.consent:
            raise ValidationError('Необходимо дать согласие на обработку персональных данных')


# from django.db.models.signals import pre_delete
# from django.dispatch import receiver

class Category(models.Model):
    category_title = models.CharField(max_length=200, unique=True, help_text='Напишите категорию для дизайна интерьера')

    def __str__(self):
        return self.category_title



    def delete(self, *args, **kwargs):
        for request in DesignRequest.objects.filter(category=self):
            request.delete()
        super(Category, self).delete(*args, **kwargs)

from django.core.validators import FileExtensionValidator, validate_image_file_extension


class DesignRequest(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    photo = models.ImageField(upload_to='design_photos/', validators=[validate_image_file_extension, FileExtensionValidator(['bmp', 'jpg', 'jpeg', 'png'], message='Allowed datatypes: bmp, jpg, jpeg, png')])
    image_design = models.ImageField(upload_to='image_designs/', validators=[validate_image_file_extension, FileExtensionValidator(['bmp', 'jpg', 'jpeg', 'png'], message='Allowed datatypes: bmp, jpg, jpeg, png')], blank=True)
    desc = models.CharField(max_length=3000)
    choices = (
        ('Новый', 'Новый'),
        ('Принято в работу', 'Принято в работу'),
        ('Выполнено', 'Выполнено'),
    )
    status = models.CharField(max_length=20, choices=choices, default='Новый', blank=True)
    comment = models.TextField(max_length=3000, help_text='Введите произвольный комментарий', blank=True)
    user = models.ForeignKey('ServUser', on_delete=models.CASCADE, null=False)
    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.title


from django.contrib import admin
class RequestAdmin(admin.ModelAdmin):
    list_display = ('category')

local/serv/forms.py
from django.contrib.auth import password_validation, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django import forms
from django.urls import reverse_lazy, reverse

from .models import ServUser, DesignRequest, Category

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

class RegisterUserForm(forms.ModelForm):
   class Meta:
       model = ServUser
       fields = ['surname', 'name', 'patronymic', 'username', 'email', 'password', 'password2', 'consent']

   email = forms.EmailField(required=True,
                            label='Адрес электронной почты')
   password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput)
   password2 = forms.CharField(label='Пароль (повторно)',
                               widget=forms.PasswordInput,
                               help_text='Повторите тот же самый пароль еще раз')


   def clean_surname(self):
       surname = self.cleaned_data['surname']
       if not surname.isalpha():
           raise forms.ValidationError("Фамилия должна состоять только из букв")
       return surname

   def clean_name(self):
       name = self.cleaned_data['name']
       if not name.isalpha():
           raise forms.ValidationError("Имя должно состоять только из букв")
       return name

   def clean_patronymic(self):
       patronymic = self.cleaned_data['patronymic']
       if not patronymic.isalpha():
           raise forms.ValidationError("Отчество должно состоять только из букв")
       return patronymic

   def clean_username(self):
       username = self.cleaned_data['username']
       if not username.isalnum():
           raise forms.ValidationError("Логин должен состоять только из латинских букв и цифр")
       if ServUser.objects.filter(username=username).exists() and not self.instance:
           raise forms.ValidationError("Пользователь с таким логином уже существует")
       return username

   def clean_email(self):
       email = self.cleaned_data['email']
       if ServUser.objects.filter(email=email).exists():
           raise forms.ValidationError("Пользователь с таким почтовым адресом уже существует")
       return email

   def clean(self):
       super().clean()
       password = self.cleaned_data.get('password')
       password2 = self.cleaned_data.get('password2')
       if password and password2 and password != password2:
           self.add_error('password2', ValidationError(
               'Введенные пароли не совпадают', code='password_mismatch'
           ))
       return self.cleaned_data

   def save(self, commit=True):
       user = super().save(commit=False)
       if 'password' in self.cleaned_data:
           user.set_password(self.cleaned_data['password'])
       user.is_active = False
       user.is_activated = False
       if commit:
           user.save()
       return user

class RequestForm(forms.ModelForm):
    user = forms.HiddenInput()
    class Meta:
       model = DesignRequest
       fields = ['title', 'category', 'desc', 'photo']
    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo:
            if photo.size > 2 * 1024 * 1024:
                raise forms.ValidationError("Это изображение превышает 2 Мб")
        return photo

    def save(self, commit=True, user=None):
        request = super().save(commit=False)
        request.user = user
        if commit:
            request.save()
        return request


class DoneFormStatus(forms.ModelForm):
    class Meta:
        model = DesignRequest
        fields = ['image_design']

    def clean_image_design(self):
        image_design = self.cleaned_data.get('image_design')
        if image_design:
            if image_design.size > 2 * 1024 * 1024:
                raise forms.ValidationError("Это изображение превышает 2 Мб")
        else:
            raise forms.ValidationError('Необходимо добавить изображение')
        return image_design

class CompletedFormStatus(forms.ModelForm):
    class Meta:
        model = DesignRequest
        fields = ['comment']
    def clean_comment(self):
        comment = self.cleaned_data.get('comment')
        if not comment:
            raise forms.ValidationError('Необходимо написать комментарий')
        return comment

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_title']

local/serv/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from django.shortcuts import render, redirect
from django.views import View

from .models import DesignRequest

from django.contrib.auth.views import LoginView

from .forms import forms, LoginUserForm, CompletedFormStatus, DoneFormStatus
from .forms import RegisterUserForm, CategoryForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from .forms import RequestForm

from django.views.generic import CreateView, DeleteView

from django.views.generic import TemplateView

from django.contrib.auth import login, authenticate

from .models import DesignRequest, ServUser, Category


def index(request):
    design_requests = DesignRequest.objects.filter(status='Выполнено').order_by('-timestamp')[:4]
    in_progress_count = DesignRequest.objects.filter(status='Принято в работу').count()
    return render(request, 'main/index.html', {'design_requests': design_requests,
                                               'in_progress_count': in_progress_count})

class LoginUser(ServUser, LoginView):
    template_name = 'main/login.html'

@login_required
def profile(request):
    status = request.GET.get('status', '')
    current_user = request.user
    design_requests = DesignRequest.objects.filter(user=current_user)
    context = {'status': status, 'design_requests': design_requests}
    return render(request, 'main/profile.html', context)
class ServLogoutView(LoginRequiredMixin, LogoutView):
   template_name = 'main/logout.html'

def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            ServUser.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                email=form.cleaned_data['email'],
                surname=form.cleaned_data['surname'],
                name=form.cleaned_data['name'],
                patronymic=form.cleaned_data['patronymic'],
            )
            messages.success(request, 'Registration successful.')
            return render(request, 'main/index.html')
    else:
        form = RegisterUserForm()
    return render(request, 'main/register_user.html', {'form': form})


from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

def all_requests(request):
    design_requests = DesignRequest.objects.all()
    return render(request, 'admin/all_requests.html', {'design_requests': design_requests})

@login_required
def request_add(request):
    if request.method == 'POST':
        form = RequestForm(request.POST, request.FILES)
        if form.is_valid():
            design_request = form.save(commit=False)
            design_request.user = request.user
            design_request.save()
            messages.add_message(request, messages.SUCCESS, 'Заявка добавлена')
            return redirect('serv:profile')
    else:
        form = RequestForm()
    return render(request, 'requests/profile_request_add.html', {'form': form })

class DeleteRequestView(LoginRequiredMixin, DeleteView):
   pk_url_kwarg = 'id'
   model = DesignRequest
   template_name = 'requests/profile_request_delete.html'
   success_url = reverse_lazy('serv:profile')

@login_required
def design_request_list(request):
    design_requests = DesignRequest.objects.filter(user=request.user)
    return render(request, 'main/profile.html', {'design_requests': design_requests})

def request_detail(request, id):
    req = get_object_or_404(DesignRequest, id=id)
    return render(request, 'admin/request_detail.html', {'request': req})

class ChangeStatusToDoneView(View):
    def get(self, request, id):
        design_request = DesignRequest.objects.get(id=id)
        form = DoneFormStatus(instance=design_request)
        return render(request, 'admin/status_done.html', {'form': form})

    def post(self, request, id):
        design_request = DesignRequest.objects.get(id=id)
        form = DoneFormStatus(request.POST, request.FILES, instance=design_request)
        if form.is_valid():
            design_request.status = 'Выполнено'
            design_request.image_design = form.cleaned_data['image_design']
            design_request.save()
            return redirect('serv:all_requests')
        return render(request, 'admin/status_done.html', {'form': form})

class ChangeStatusToCompletedView(View):
    def get(self, request, id):
        design_request = DesignRequest.objects.get(id=id)
        form = CompletedFormStatus(instance=design_request)
        return render(request, 'admin/status_completed.html', {'form': form})

    def post(self, request, id):
        design_request = DesignRequest.objects.get(id=id)
        form = CompletedFormStatus(request.POST, instance=design_request)
        if form.is_valid():
            design_request.status = 'Принято в работу'
            design_request.comment = form.cleaned_data['comment']
            design_request.save()
            return redirect('serv:all_requests')
        return render(request, 'admin/status_completed.html', {'form': form})

def category_list(request):
    categories = Category.objects.all()
    return render(request, 'admin/category_list.html', {'categories': categories})

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Категория добавлена')
            return redirect('serv:category_list')
    else:
        form = CategoryForm()
    return render(request, 'admin/add_category.html', {'form': form})

class DeleteCategoryView(LoginRequiredMixin, DeleteView):
   pk_url_kwarg = 'id'
   model = Category
   template_name = 'admin/category_delete.html'
   success_url = reverse_lazy('serv:category_list')

local/serv/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
  <h2>Последние 4 заявки</h2>
  {% for request in design_requests %}

    <div class="card" style="width: 22rem; margin: 23px;">
        <img src="{{ request.photo.url }}" alt="{{ design_request.title }}" class="card-img-top">
      <div class="card-body">
        <p class="card-text">Дата: {{ request.timestamp }}</p>
        <p class="card-text">Название: {{ request.title }}</p>
        <p class="card-text">Категория заявки: {{ request.category }}</p>
      </div>
    </div>
  {% empty %}
    <p>Нет доступных заявок</p>
  {% endfor %}

  <footer class="mt-3 border-top">
      <small class="p-2">
          <p>Количество заявок в статусе "Принято в работу": {{ in_progress_count }}</p>
      </small>
  </footer>
{% endblock %}

local/serv/templates/main/login.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Вход {% endblock %}


{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="POST">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   <input type="hidden" name="next" value="{{ next }}">
   {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %}

local/serv/templates/main/logout.html
{% extends "layout/basic.html" %}


{% block title %} Выход {% endblock %}


{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

local/serv/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Профиль пользователя {% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.surname and user.name %}
<p>Здравствуйте, {{ user.surname }} {{ user.name }} </p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<button type="button" class="btn btn-outline-primary"><a href="{% url 'serv:request_add' %}">Добавить</a></button>
<h3>Ваши заявки</h3>

<h3>Статус:</h3>
<form method="GET">
    <select class="dropdown-item" name="status">
        <option value="">Все</option>
        <option value="Новый">Новый</option>
        <option value="Принято в работу">Принято в работу</option>
        <option value="Выполнено">Выполнено</option>
    </select>
    <button type="submit" class="btn btn-primary">Фильтровать</button>
</form>

{% if status == 'Новый' %}
    <h2>Новые заявки</h2>
    {% for request in design_requests %}
    {% if request.status == 'Новый' %}
    <div class="card" style="width: 22rem; margin: 23px;">
        <div class="card-body">
            <p class="card-text">Дата: {{ request.timestamp }}</p>
            <p class="card-text">Название: {{ request.title }}</p>
            <p>Описание: {{ request.desc }}</p>
            <p class="card-text">Категория заявки: {{ request.category }}</p>
            <p class="card-text">Статус: {{ request.status }}</p>

            <button type="button" class="btn btn-outline-danger">
                <a href="{% url 'serv:profile_request_delete' id=request.id %}">Удалить</a></button>
        </div>
    </div>
    {% endif %}
    {% endfor %}
{% elif status == 'Принято в работу' %}
    <h2>Принятые в работу</h2>
    {% for request in design_requests %}
    {% if request.status == 'Принято в работу' %}
    <div class="card" style="width: 22rem; margin: 23px;">
        <div class="card-body">
            <p class="card-text">Дата: {{ request.timestamp }}</p>
            <p class="card-text">Название: {{ request.title }}</p>
            <p>Описание: {{ request.desc }}</p>
            <p class="card-text">Категория заявки: {{ request.category }}</p>
            <p class="card-text">Статус: {{ request.status }}</p>

            <button type="button" class="btn btn-outline-danger">
                <a href="{% url 'serv:profile_request_delete' id=request.id %}">Удалить</a>
            </button>
        </div>
    </div>
    {% endif %}
    {% endfor %}
{% elif status == 'Выполнено' %}
    <h2>Выполненные заявки</h2>
    {% for request in design_requests %}
    {% if request.status == 'Выполнено' %}
    <div class="card" style="width: 22rem; margin: 23px;">
        <div class="card-body">
            <p class="card-text">Дата: {{ request.timestamp }}</p>
            <p class="card-text">Название: {{ request.title }}</p>
            <p>Описание: {{ request.desc }}</p>
            <p class="card-text">Категория заявки: {{ request.category }}</p>
            <p class="card-text">Статус: {{ request.status }}</p>

            <button type="button" class="btn btn-outline-danger">
                <a href="{% url 'serv:profile_request_delete' id=request.id %}">Удалить</a>
            </button>
        </div>
    </div>
    {% endif %}
    {% endfor %}
{% else %}
    <h2>Все заявки</h2>
    {% for request in design_requests %}
    <div class="card" style="width: 22rem; margin: 23px;">
        <div class="card-body">
            <p>Описание: {{ request.desc }}</p>
            <p class="card-text">Дата: {{ request.timestamp }}</p>
            <p class="card-text">Название: {{ request.title }}</p>
            <p class="card-text">Описание: {{ request.desc }}</p>
            <p class="card-text">Категория заявки: {{ request.category }}</p>
            <p class="card-text">Статус: {{ request.status }}</p>

            <button type="button" class="btn btn-outline-danger">
                <a href="{% url 'serv:profile_request_delete' id=request.id %}">Удалить</a>
            </button>
        </div>
    </div>
    {% endfor %}
{% endif %}
{% endblock %}

local/serv/templates/main/register_user.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Регистрация {% endblock %}


{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="POST" novalidate>
	{% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
   {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
</form>

{% endblock content%}